name: Deno Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      IMAP_HOST: ${{ secrets.IMAP_HOST }}
      IMAP_PORT: ${{ secrets.IMAP_PORT }}
      IMAP_USERNAME: ${{ secrets.IMAP_USERNAME }}
      IMAP_PASSWORD: ${{ secrets.IMAP_PASSWORD }}
      IMAP_USE_TLS: ${{ secrets.IMAP_USE_TLS }}

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno test --allow-net --allow-env
